version: "latest"
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports: 
      - 3000:3000
    depends_on:
      - board-db

  frontend:
    build: ./frontend
    ports: 
      - 2094:2094
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  board-db:
    image: postgres:latest
    volumes:
      - whiteboard-db:/var/lib/postgresql
      - ./data/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432

volumes: 
  whiteboard-db: 
    
